using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Text;
using CaYaTunnel.Server.Routing;
using Xunit;

namespace CaYaTunnel.Tests;

public class ProtocolSnifferTests
{
    [Fact]
    public async Task Sni_is_read_from_a_real_TLS_client_hello()
    {
        // Generated by the actual TLS stack rather than a handcrafted buffer, so the parser is
        // tested against what real clients send.
        var listener = new TcpListener(IPAddress.Loopback, 0);
        listener.Start();
        var port = ((IPEndPoint)listener.LocalEndpoint).Port;

        var accepting = listener.AcceptTcpClientAsync();

        using var client = new TcpClient();
        await client.ConnectAsync(IPAddress.Loopback, port);

        // Never completes — the "server" only reads the hello — so it runs unobserved.
        _ = Task.Run(async () =>
        {
            try
            {
                await using var tls = new SslStream(client.GetStream(), false, (_, _, _, _) => true);
                await tls.AuthenticateAsClientAsync("panel.tunnel.example.com");
            }
            catch (Exception ex) when (ex is IOException or AuthenticationException or ObjectDisposedException)
            {
                // Expected: nobody is answering the handshake.
            }
        });

        using var accepted = await accepting;
        var buffer = new byte[4096];
        var read = await accepted.GetStream().ReadAsync(buffer).AsTask().WaitAsync(TimeSpan.FromSeconds(15));

        listener.Stop();

        Assert.True(ProtocolSniffers.LooksLikeTls(buffer.AsSpan(0, read)));
        Assert.Equal("panel.tunnel.example.com", ProtocolSniffers.ReadTlsSni(buffer.AsSpan(0, read)));
    }

    [Fact]
    public void Truncated_or_junk_bytes_never_throw()
    {
        Assert.Null(ProtocolSniffers.ReadTlsSni([]));
        Assert.Null(ProtocolSniffers.ReadTlsSni([0x16]));
        Assert.Null(ProtocolSniffers.ReadTlsSni([0x16, 0x03, 0x01, 0xFF, 0xFF, 0x01]));
        Assert.Null(ProtocolSniffers.ReadTlsSni("GET / HTTP/1.1\r\n\r\n"u8));
        Assert.Null(ProtocolSniffers.ReadMinecraftHostname([0xFF, 0xFF, 0xFF]));
        Assert.Null(ProtocolSniffers.ReadHttpHost("not http at all"u8));
    }

    [Theory]
    [InlineData("GET / HTTP/1.1\r\nHost: panel.example.com\r\n\r\n", "panel.example.com")]
    [InlineData("GET / HTTP/1.1\r\nhost: PANEL.example.com\r\n\r\n", "panel.example.com")]
    [InlineData("POST /x HTTP/1.1\r\nUser-Agent: x\r\nHost: a.b.c:8080\r\n\r\n", "a.b.c")]
    [InlineData("GET / HTTP/1.1\r\nHost:   spaced.example.com  \r\nX: y\r\n\r\n", "spaced.example.com")]
    public void Host_header_is_read_and_normalised(string request, string expected)
    {
        var host = ProtocolSniffers.ReadHttpHost(Encoding.ASCII.GetBytes(request));
        Assert.Equal(expected, host);
    }

    [Fact]
    public void A_request_without_a_host_header_yields_null()
    {
        Assert.Null(ProtocolSniffers.ReadHttpHost("GET / HTTP/1.0\r\nAccept: */*\r\n\r\n"u8));
    }

    [Theory]
    [InlineData("mc.tunnel.example.com", 25565)]
    [InlineData("survival.example.org", 25565)]
    public void Minecraft_handshake_yields_the_address_the_player_typed(string hostname, ushort port)
    {
        var packet = BuildMinecraftHandshake(hostname, port, protocolVersion: 767, nextState: 2);

        Assert.True(ProtocolSniffers.HasCompleteMinecraftHandshake(packet));
        Assert.Equal(hostname, ProtocolSniffers.ReadMinecraftHostname(packet));
    }

    [Fact]
    public void Forge_and_proxy_suffixes_are_stripped_from_the_address()
    {
        // Forge appends "\0FML\0"; BungeeCord appends the player's ip and uuid the same way.
        var forge = BuildMinecraftHandshake("mc.example.com\0FML\0", 25565, 767, 2);
        Assert.Equal("mc.example.com", ProtocolSniffers.ReadMinecraftHostname(forge));

        var bungee = BuildMinecraftHandshake("mc.example.com\0203.0.113.5\0abc-def", 25565, 767, 2);
        Assert.Equal("mc.example.com", ProtocolSniffers.ReadMinecraftHostname(bungee));
    }

    [Fact]
    public void A_partial_handshake_is_reported_as_incomplete_rather_than_guessed()
    {
        var full = BuildMinecraftHandshake("mc.example.com", 25565, 767, 2);
        var partial = full[..6];

        Assert.False(ProtocolSniffers.HasCompleteMinecraftHandshake(partial));
    }

    [Fact]
    public void Legacy_ping_is_recognised_as_unroutable_instead_of_being_misparsed()
    {
        Assert.Null(ProtocolSniffers.ReadMinecraftHostname([0xFE, 0x01]));
    }

    internal static byte[] BuildMinecraftHandshake(string address, ushort port, int protocolVersion, int nextState)
    {
        var body = new List<byte>();
        WriteVarInt(body, 0x00); // packet id
        WriteVarInt(body, protocolVersion);

        var addressBytes = Encoding.UTF8.GetBytes(address);
        WriteVarInt(body, addressBytes.Length);
        body.AddRange(addressBytes);

        body.Add((byte)(port >> 8));
        body.Add((byte)(port & 0xFF));
        WriteVarInt(body, nextState);

        var packet = new List<byte>();
        WriteVarInt(packet, body.Count);
        packet.AddRange(body);
        return [.. packet];
    }

    private static void WriteVarInt(List<byte> output, int value)
    {
        var remaining = (uint)value;
        while (true)
        {
            if ((remaining & ~0x7Fu) == 0)
            {
                output.Add((byte)remaining);
                return;
            }

            output.Add((byte)((remaining & 0x7F) | 0x80));
            remaining >>= 7;
        }
    }
}
