<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CaYaTunnel.Client</RootNamespace>
    <AssemblyName>CaYaTunnel.Client</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaYaTunnel.Core\CaYaTunnel.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CaYaTunnel.Core.Tests" />
  </ItemGroup>

</Project>
